### ISSUE TITLE
GcmIOS.addListener is not a function

### ISSUE THREAD

**Issue by ericsanjaya** [cmcewen/react-native-gcm-ios#1]
i have problem with react-native-gcm-ios. i follow instruction but i have error GcmIOS.addListener is not a function. can some one tell me what wrong?
have someone succes use react-native-gcm-ios?
i install using pod like article link in readme.

i use react native 0.19

after couple of hour i solve it by editing index.ios.js file :
at the end line (65) of file i change 
'export default GcmIOS' to 'module.exports = GcmIOS'

mybe this can help other

**Comment by cmcewen** [comment]
Are you using a different `.babelrc` in your project?

**Comment by ericsanjaya** [comment]
@cmcewen no, i dont use .babelrc, and i don't know what it .babelrc

**Comment by cmcewen** [comment]
@ericsanjaya try `import GcmIOS from 'react-native-gcm-ios'` - I updated the docs

**Comment by ericsanjaya** [comment]
@cmcewen it worked well, thanks for your hard work
